name: TimeUp Mac

on:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-26-intel

    steps:
      - name: Check Mac
        run: |
          sw_vers
          uname -m
          xcodebuild -version
          system_profiler SPHardwareDataType

      - name: Connect Mac to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest
          use-cache: 'false'

      - name: Enable Tailscale SSH
        run: sudo tailscale set --ssh

      - name: Keep Mac alive
        run: sleep 3600
